export const evidencePlannerPolicyCatalog = {
  wildfire: {
    id: "wildfire_evidence_policy_v1",
    taskId: "wildfire",
    summary: "以当前成熟热异常链为主，在高不确定场景下主动引入静态热异常掩膜、时间连续性和高分补充。",
    selectTopK: 3,
    maxIterations: 4,
    stopThresholds: {
      confidenceEnough: 0.74,
      marginalGainTooSmall: 0.04,
      uncertaintyHigh: 0.42,
      minBudgetLatencyMs: 900,
    },
    weights: {
      taskRelevance: 0.24,
      expectedInformationGain: 0.18,
      complementarity: 0.1,
      temporalContinuity: 0.16,
      spatialContinuity: 0.1,
      latencyPenalty: 0.08,
      computePenalty: 0.04,
      lowQualityPenalty: 0.05,
      redundancyPenalty: 0.05,
    },
    actionGroups: [
      "visual",
      "quality",
      "thermal",
      "temporal",
      "static-prior",
      "highres",
      "finalize",
    ],
    contextActions: [
      "choose_visual_source",
      "fetch_cloud_guidance",
      "build_valid_region",
      "fetch_viirs_active_fire",
      "fetch_static_thermal_anomaly_mask",
      "temporal_persistence_check",
      "request_highres_support",
      "cluster_hotspots",
      "local_burned_area_refine",
      "uncertainty_check",
      "package_result",
    ],
    scoringFeatures: {
      thermalStrengthWeight: 0.34,
      clearSkyWeight: 0.18,
      temporalPersistenceWeight: 0.2,
      staticMaskPenaltyWeight: 0.14,
      landWaterCompatibilityWeight: 0.08,
      highresAvailabilityWeight: 0.06,
      estimatedLatencyWeight: 0.12,
    },
  },
  dust: {
    id: "dust_evidence_policy_v1",
    taskId: "dust",
    summary: "把 support/screening 推进为硬 veto + 时序连续性校验，无法区分时优先 abstain 或 degrade。",
    selectTopK: 3,
    maxIterations: 4,
    stopThresholds: {
      confidenceEnough: 0.7,
      marginalGainTooSmall: 0.035,
      uncertaintyHigh: 0.45,
      minBudgetLatencyMs: 1200,
    },
    weights: {
      taskRelevance: 0.24,
      expectedInformationGain: 0.18,
      complementarity: 0.08,
      temporalContinuity: 0.18,
      spatialContinuity: 0.12,
      latencyPenalty: 0.08,
      computePenalty: 0.04,
      lowQualityPenalty: 0.04,
      redundancyPenalty: 0.04,
    },
    actionGroups: [
      "visual",
      "quality",
      "support-prior",
      "screening",
      "temporal",
      "dust-score",
      "fallback",
      "finalize",
    ],
    contextActions: [
      "choose_visual_source",
      "fetch_cloud_guidance",
      "build_valid_region",
      "fetch_land_water_mask",
      "fetch_dust_support_priors",
      "score_dust_candidates",
      "reject_water_like_candidates",
      "temporal_continuation_check",
      "dust_window_fallback",
      "uncertainty_check",
      "package_result",
    ],
    scoringFeatures: {
      dustPriorSupportWeight: 0.32,
      waterCloudVetoPenaltyWeight: 0.24,
      temporalContinuityWeight: 0.18,
      sourceRegionConsistencyWeight: 0.12,
      validRegionCoverageWeight: 0.14,
      estimatedLatencyWeight: 0.1,
    },
  },
};

export function getEvidencePlannerPolicy(taskId) {
  return evidencePlannerPolicyCatalog[taskId] || null;
}
