export const scenarios = [
  {
    id: "dust-frontier",
    title: "河西沙尘锋面",
    type: "dust",
    mission: "优先锁定沙尘锋面核心区，在 6 分钟内给出可用的反演摘要。",
    sensor: "静止轨道光学载荷",
    defaultBudgetMin: 6,
    defaultPowerMode: "balanced",
    cloudCover: 0.22,
    radiometricQuality: 0.73,
    lowContrast: false,
    anomalyDensity: 0.72,
    bandwidthBudgetMb: 28,
    imagery: {
      src: "./assets/images/dust-storm.jpg",
      aspectRatio: "1786 / 1191",
      credit: "底图来源：NASA Earth Observatory",
    },
    description:
      "沙尘带范围较大，如果全场景按统一流程处理，很容易把星上时延拖长，适合展示重点区域优先反演。",
    rois: [
      {
        id: "R1",
        name: "锋面核心区",
        risk: 0.95,
        signal: 0.87,
        cloud: 0.12,
        area: 180,
        box: { left: 22, top: 56, width: 28, height: 20 },
      },
      {
        id: "R2",
        name: "东缘扩散区",
        risk: 0.76,
        signal: 0.72,
        cloud: 0.18,
        area: 150,
        box: { left: 45, top: 43, width: 18, height: 16 },
      },
      {
        id: "R3",
        name: "尾迹稀疏区",
        risk: 0.56,
        signal: 0.51,
        cloud: 0.09,
        area: 110,
        box: { left: 57, top: 36, width: 12, height: 12 },
      },
      {
        id: "R4",
        name: "北侧带状区",
        risk: 0.67,
        signal: 0.61,
        cloud: 0.16,
        area: 140,
        box: { left: 66, top: 29, width: 16, height: 14 },
      },
    ],
  },
  {
    id: "urban-plume",
    title: "三角洲城市污染羽流",
    type: "pollution",
    mission: "优先筛查城市污染羽流，只对高风险区域触发 PM 反演，并控制下传负载。",
    sensor: "静止轨道光学载荷",
    defaultBudgetMin: 7,
    defaultPowerMode: "constrained",
    cloudCover: 0.42,
    radiometricQuality: 0.69,
    lowContrast: false,
    anomalyDensity: 0.66,
    bandwidthBudgetMb: 22,
    imagery: {
      src: "./assets/images/urban-plume.jpg",
      aspectRatio: "3 / 2",
      credit: "底图来源：NASA Earth Observatory",
    },
    description:
      "污染异常呈条带扩散，且云污染接近阈值。标准流程容易在质量筛查阶段失败，适合演示插入云掩膜的修复动作。",
    rois: [
      {
        id: "R1",
        name: "西侧污染带",
        risk: 0.91,
        signal: 0.79,
        cloud: 0.39,
        area: 120,
        box: { left: 15, top: 20, width: 24, height: 20 },
      },
      {
        id: "R2",
        name: "中部主羽流",
        risk: 0.88,
        signal: 0.74,
        cloud: 0.33,
        area: 155,
        box: { left: 39, top: 34, width: 23, height: 20 },
      },
      {
        id: "R3",
        name: "东侧扩散区",
        risk: 0.63,
        signal: 0.58,
        cloud: 0.28,
        area: 105,
        box: { left: 60, top: 42, width: 18, height: 18 },
      },
      {
        id: "R4",
        name: "南向尾迹区",
        risk: 0.58,
        signal: 0.49,
        cloud: 0.43,
        area: 95,
        box: { left: 63, top: 59, width: 18, height: 17 },
      },
    ],
  },
  {
    id: "twilight-edge",
    title: "暮光混合异常",
    type: "mixed",
    mission: "在短预算下判断是否值得做定量产品，必要时主动降级为异常热区简报。",
    sensor: "低轨多光谱载荷",
    defaultBudgetMin: 5,
    defaultPowerMode: "constrained",
    cloudCover: 0.18,
    radiometricQuality: 0.52,
    lowContrast: true,
    anomalyDensity: 0.54,
    bandwidthBudgetMb: 18,
    imagery: {
      src: "./assets/images/twilight-haze.jpg",
      aspectRatio: "1 / 1",
      credit: "底图来源：NASA Earth Observatory",
    },
    description:
      "暮光条件导致信噪比偏低，强行做标准反演容易出现低置信输出，适合展示质量降级策略。",
    rois: [
      {
        id: "R1",
        name: "混合核心区",
        risk: 0.82,
        signal: 0.57,
        cloud: 0.15,
        area: 98,
        box: { left: 39, top: 31, width: 18, height: 18 },
      },
      {
        id: "R2",
        name: "东侧扩散区",
        risk: 0.64,
        signal: 0.48,
        cloud: 0.11,
        area: 88,
        box: { left: 60, top: 45, width: 18, height: 16 },
      },
      {
        id: "R3",
        name: "南部边缘区",
        risk: 0.53,
        signal: 0.44,
        cloud: 0.18,
        area: 72,
        box: { left: 43, top: 60, width: 15, height: 14 },
      },
    ],
  },
];

export function getScenarioById(id) {
  return scenarios.find((scenario) => scenario.id === id) ?? scenarios[0];
}
